### ISSUE TITLE
Use @webref/idl

### ISSUE THREAD

**Issue by foolip** [saschanaz/types-web#66]
https://www.npmjs.com/package/@webref/idl

This package has fixed IDL files with certain guarantees, which I suspect could make it easier to maintain this package.

If this repo also contains code to apply partials and mixins, then maybe we should put that in the package too.

**Comment by saschanaz** [comment]
Currently this repo also uses CSS part, which I believe is not covered yet:

https://github.com/saschanaz/types-web/blob/076ca2b1e28c4b68299901bd3c782a3f192d10c0/src/build/webref.ts#L6-L9

>If this repo also contains code to apply partials and mixins, then maybe we should put that in the package too.

Wait, does the package exclude them? Didn't know that 🤔

**Comment by foolip** [comment]
I've sent https://github.com/w3c/webref/issues/111 for publishing CSS. I don't know which bits you use, but I guess if we publish everything in ed/css/ it will work for you?

> Wait, does the package exclude them? Didn't know that 🤔

No, all the IDL is included as-is from specs with only the minimal fixes needed. But to actually interpret it, one has to apply partials and mixins, code which I've now written in multiple places. Here's the best I have:
https://github.com/foolip/mdn-bcd-collector/blob/c0a50a1fbd5ce5195c918aee360c7ec4edf84a02/build.js#L222

Have you also written this kind of code? If so, adding it to `@webref/idl` might make sense.

**Comment by saschanaz** [comment]
#10 is about mixins, but since the code needs not to flatten mixins, the patch tries to resolve the mixin support data from base interface support data. I think being able to access the new jsons for mixin in BCD could simplify the patch.

**Comment by foolip** [comment]
Ah, I see. BCD does have some mixins now, but also lots of things that are flattened, so it's really not straightforward to interpret it alongside IDL definitions, one would have to try matching both the mixin names and the real interface names I guess.

Waiting until BCD has no mixins sounds smart :)
