### ISSUE TITLE
Get HTML/SVG tagname data from webref?

### ISSUE THREAD

**Issue by saschanaz** [saschanaz/types-web#76]
Currently `addedTypes.json` manually adds element-to-interface mapping.

@foolip I do see the relevant `"type": "element"` items but not sure they are mappable to IDL interfaces as of now. Do you think this is doable?

**Comment by foolip** [comment]
Is the data you'd like the same as in https://html.spec.whatwg.org/multipage/indices.html#element-interfaces, but scraped and not manually maintained?

**Comment by saschanaz** [comment]
Exactly, and also from SVG specs.

**Comment by foolip** [comment]
I agree this would be useful. Can you file an issue in webref? I really doubt this can be extracted from the existing data.

**Comment by saschanaz** [comment]
f50eeeb98af377b82001cb5eff22904855d753c5. Thanks!
